### ISSUE TITLE
release missing

### ISSUE THREAD

**Issue by pelikhan** [Tinkertanker/pxt-oled-ssd1306#11]
You need to create a github tag for each release. Use ``pxt bump`` to automate the process.

**Comment by nioq** [comment]
Actually we have been tagging the versions but hadn't consistently been creating a *release* in the GitHub sense (https://github.com/Tinkertanker/pxt-oled-ssd1306/releases). Pretty sure yesterday's push was tagged too as the fix was picked up by official Makecode with the right tag #1.2.4

`pxt bump` saves time but also doesn't seem to create a release. Am I missing something or is the manual step of creating a GitHub release (with downloadable source .zip) actually necessary?

Thanks!

**Comment by pelikhan** [comment]
We just need a tag, not .tgz necessary.

**Comment by pelikhan** [comment]
So right now your lib is snapped to v1.2.3 in v0

**Comment by nioq** [comment]
is tagged. ok to keep v0 snapped to v1.2.3
